image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - muhammad-sammy.csharp@1.23.6:BePnSiVYh1NffvJF07AGvQ==
    - jsw.csharpextensions@1.3.6:hLCmZ4eAX9pbCaxe9T4hsQ==